checks:
  php: true


filter:
  paths:
    - 'src/'


build:
  environment:
    php:
      version: '7.2'

    docker: true

    dependencies:
      before:
        - make start
        - curl -O http://packages.couchbase.com/releases/couchbase-release/couchbase-release-1.0-4-amd64.deb
        - sudo dpkg -i couchbase-release-1.0-4-amd64.deb
        - sudo apt-get update
        - sudo apt-get install -y libcouchbase-dev build-essential zlib1g-dev
        - pecl install couchbase

    tests:
      override:
        - command: TEST_COUCHBASE_HOST=$DOCKER_IP composer run
          coverage:
            file: report/coverage/clover.yml
            format: php-clover
