language: php

sudo: required

services:
  - docker

php:
  - '5.6'
  - '7.0'
  - '7.1'
  - '7.2'

env:
  - TEST_COUCHBASE_HOST: 127.0.0.1

before_install:
  # start couchbase server
  - make start
  # install couchbase SDK
  - curl -O http://packages.couchbase.com/releases/couchbase-release/couchbase-release-1.0-4-amd64.deb
  - sudo dpkg -i couchbase-release-1.0-4-amd64.deb
  - sudo apt-get update
  - sudo apt-get install -y libcouchbase-dev build-essential zlib1g-dev
  - pecl install couchbase

install:
  - rm composer.lock
  - composer install --no-interaction

before_script:
  - command -v phpdbg > /dev/null || sed -i -e 's/phpdbg -qrr //g' composer.json

script:
  - composer test

after_script:
  - ./bin/couchbase-server -k
